# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa36a84352676b117ffd8afef133fb1582cd79ca5b80e1e548f3881e2ae9ea14eeb1d495157a10f6f0ecb41006dd197e83d0b60c239bd5f0717a3f81aaf20d22

test:
  secret_key_base: fe76168dcf8f3c87d60fda6c48b3c8894c28d0ef33b09a6efd671c1688d17000f662900db7b40f5b8ea8d82a30ceec7de5bd9902759c6faa1fb7b7d14e37f396

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
